//
//  File.swift
//  Quark
//
//  Created by Yeskendir Salgara on 15/05/2025.
//

import Foundation
import PackagePlugin

@main
struct QuarkTestsPlugin: BuildToolPlugin {
    func createBuildCommands(context: PluginContext, target: Target) async throws -> [Command] {
        print("[QuarkTestsPlugin] Plugin started for target: \(target.name)")
        
        // Get the test target that's using this plugin
        guard let testTarget = target as? SourceModuleTarget else {
            print("[QuarkTestsPlugin] Target is not a source module target")
            return []
        }
        
        // Find all targets that this test target depends on
        let testedTargets = findTestedTargets(in: context.package, for: testTarget)
        
        let targetNames = testedTargets.compactMap { $0 as? SourceModuleTarget }.map { $0.name }
        print("[QuarkTestsPlugin] Found tested targets: \(targetNames.joined(separator: ", "))")
        
        // Generate tests in the plugin's work directory
        let outputDir = context.pluginWorkDirectory.appending("GeneratedTests")
        try FileManager.default.createDirectory(at: URL(fileURLWithPath: outputDir.string), withIntermediateDirectories: true)
        
        var commands: [Command] = []
        
        // Create a test file that will import all generated tests
        let testIndexContent = generateTestIndex(for: testedTargets)
        let testIndexPath = outputDir.appending("GeneratedTestsIndex.swift")
        try testIndexContent.write(to: URL(fileURLWithPath: testIndexPath.string), atomically: true, encoding: .utf8)
        
        // Add the index file to the output files
        commands.append(
            .buildCommand(
                displayName: "Generate tests index",
                executable: .init("/bin/echo"),
                arguments: ["Generated tests index"],
                outputFiles: [testIndexPath]
            )
        )
        
        // Keep track of which test files we generate
        var generatedTestFiles: Set<String> = []
        
        // Scan files in all tested targets
        for testedTarget in testedTargets {
            guard let sourceTarget = testedTarget as? SourceModuleTarget else { continue }
            
            print("[QuarkTestsPlugin] Scanning files in target: \(sourceTarget.name)")
            
            for file in sourceTarget.sourceFiles(withSuffix: ".swift") {
                print("[QuarkTestsPlugin] Checking file: \(file.url.path)")
                let content = try String(contentsOfFile: file.url.path)
                
                // Look for both the macro and its expanded form
                guard content.contains("@QuarkLocalize") else { continue }
                
                print("[QuarkTestsPlugin] Found localization tracking in: \(file.url.lastPathComponent)")
                
                // Extract the view name from the file content
                let viewName = extractViewName(from: content) ?? file.url.deletingPathExtension().lastPathComponent
                let testFilePath = outputDir.appending("\(viewName)Tests.swift")
                let testContent = generateLocalizationTestContent(for: viewName, target: sourceTarget.name)
                
                try testContent.write(to: URL(fileURLWithPath: testFilePath.string), atomically: true, encoding: .utf8)
                print("[QuarkTestsPlugin] Generated test: \(testFilePath.string)")
                
                generatedTestFiles.insert(testFilePath.string)
                
                // Add the generated test file to the output files
                commands.append(
                    .buildCommand(
                        displayName: "Generate localization test for \(viewName)",
                        executable: .init("/bin/echo"),
                        arguments: ["Generated test for \(viewName)"],
                        outputFiles: [testFilePath]
                    )
                )
            }
        }
        
        // Clean up old test files that are no longer needed
        let fileManager = FileManager.default
        if let existingFiles = try? fileManager.contentsOfDirectory(atPath: outputDir.string) {
            for file in existingFiles {
                let filePath = outputDir.appending(file).string
                if file.hasSuffix("Tests.swift") && !generatedTestFiles.contains(filePath) {
                    try? fileManager.removeItem(atPath: filePath)
                    print("[QuarkTestsPlugin] Removed old test file: \(file)")
                }
            }
        }
        
        return commands
    }
    
    private func generateTestIndex(for targets: [Target]) -> String {
        """
        import XCTest
        import SwiftUI
        
        // This file is automatically generated by QuarkTestsPlugin
        
        // This ensures all tests are included in the test target
        final class GeneratedTestsIndex: XCTestCase {
            func testGeneratedTestsAreIncluded() {
                XCTAssertTrue(true, "This test ensures all generated tests are included in the test target")
            }
        }
        """
    }
    
    private func findTestedTargets(in package: Package, for testTarget: SourceModuleTarget) -> [Target] {
        var testedTargets: [Target] = []
        
        // Get all dependencies of the test target
        for dependency in testTarget.dependencies {
            switch dependency {
            case .target(let target):
                // Find the target in the package
                if let target = package.targets.first(where: { $0.name == target.name }) {
                    testedTargets.append(target)
                }
            case .product(let target):
                // Find the product in the package
                if let product = package.products.first(where: { $0.name == target.name }),
                   let target = package.targets.first(where: { $0.name == product.name })
                {
                    testedTargets.append(target)
                }
            @unknown default:
                assertionFailure("Didn't expect to have dependency \(dependency)")
            }
        }
        
        return testedTargets
    }
    
    private func generateLocalizationTestContent(for viewName: String, target: String) -> String {
        """
        //
        //  \(viewName)Tests.swift
        //  \(target)
        //
        //  Created by Yeskendir Salgara on 25/05/2025.
        //

        import Foundation
        @testable import \(target)
        import SwiftUI
        import ViewInspector
        import XCTest

        @MainActor
        final class Quark\(viewName)L10nTests: XCTestCase {
            func testTranslations() {
                #if SWIFT_PACKAGE
                    let bundle = Bundle.module
                #else
                    let bundle = Bundle.main
                #endif
                
                let supportedLocales = bundle.localizations
                let sut = \(viewName)()

                do {
                    let parent = try sut.inspect().implicitAnyView()
                    let textElements = parent.findAll(ViewType.Text.self)
                    for locale in supportedLocales {
                        let stringsPath = bundle.path(forResource: "Localizable",
                                                      ofType: "strings",
                                                      inDirectory: nil,
                                                      forLocalization: locale)
                        let dictionary = NSDictionary(contentsOfFile: stringsPath ?? "")

                        for textElement in textElements {
                            let string = try textElement.string(locale: Locale(identifier: locale))
                            guard let value = dictionary?.first(where: { ($0.value as? String ?? "") == string })?.value as? String else {
                                XCTFail("No translation found for \\(locale) - value: \\(string)")
                                return
                            }

                            XCTAssertEqual(string, value)
                        }
                    }
                } catch {
                    XCTFail("Test failed: \\(String(describing: error))")
                }
            }
        }
        """
    }
    
    private func extractViewName(from content: String) -> String? {
        // Look for struct definitions that are marked with @QuarkLocalize
        let lines = content.components(separatedBy: .newlines)
        for line in lines {
            if line.contains("@QuarkLocalize") {
                // Find the next line that contains "struct" and extract the name
                if let structLine = lines.first(where: { $0.contains("struct") && $0.contains(": View") }) {
                    let components = structLine.components(separatedBy: "struct")
                    if components.count > 1 {
                        let nameComponent = components[1].components(separatedBy: ":")[0].trimmingCharacters(in: .whitespaces)
                        return nameComponent
                    }
                }
            }
        }
        return nil
    }
}
